name: "prod_cluster_a"
type: "isolated"
resources:
  cpu: 4
  memory: "16Gi"

tools:
  sysbench: "/usr/local/bin/sysbench"
  ramspeed: "/usr/local/bin/ramspeed"
  memory_latency: "/usr/local/bin/mlc"

storage:
  path: "/data/benchmark/results"
  format: "sqlite"

credentials:
  username: "admin"
  password: "admin"
  host: "localhost"
  port: 5432
  database: "test_results"

infrastructure:
  vcf: "4.2.1"
  nsx_t: "3.1.1"
  vcenter: "7.0.2"
  esxi: "7.0.2"